apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: default
  labels:
    app: ${SERVICE_NAME_LOWERCASE}

data:
  JWT_SECRET: "${JWT_SECRET}"
  JWT_EXPIRATION: "${JWT_EXPIRATION:-3600000}"