apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME_LOWERCASE}
spec:
  type: ClusterIP
  selector:
    app: ${SERVICE_NAME_LOWERCASE}
  ports:
  - protocol: TCP
    port: 80
    targetPort: ${{ inputs.container-port }}
