apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 80
          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: orderservice
                port:
                  number: 80
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: userservice
                port:
                  number: 80
          - path: /api/worker
            pathType: Prefix
            backend:
              service:
                name: workerservice
                port:
                  number: 80