name: Common Build Steps for Java Spring Boot Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
     
      - name: Build and Run Tests 
        run: |
          if [ -f "./mvnw" ] && [ -f "./.mvn/wrapper/maven-wrapper.properties" ]; then
            echo "Running tests with Maven Wrapper..."
            chmod +x ./mvnw
            ./mvnw clean package -DskipTests
          else
            echo "Maven Wrapper not found. Using system Maven..."
            mvn clean package -DskipTests
          fi



