name: Common Build Steps for Java Spring Boot Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SAST Scan
        uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/sast-scan.yml@main
        with:
          service-name: ${{ inputs.service-name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Run Tests (with fallback)
        run: |
          if [ -f "./mvnw" ] && [ -f "./.mvn/wrapper/maven-wrapper.properties" ]; then
            echo "Using Maven Wrapper to build and test"
            chmod +x ./mvnw
            ./mvnw clean install -DskipTests
          else
            echo "Maven wrapper not found, using system Maven"
            mvn clean install -DskipTests
          fi
