name: Common Build Steps for Java Spring Boot Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
    
      - name: Make mvnw executable
        run: chmod +x ${{ inputs.service-name }}/mvnw

      - name: Build and Run Tests
        run: |
          cd ${{ inputs.service-name }}
          ./mvnw clean verify
