name: Build and Deploy Java Spring Boot Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      container-port:
        required: false
        type: string
        default: "8080"
    secrets:
      GCP_SA_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true
      GCP_REGION:
        required: true
      GCP_CLUSTER_NAME:
        required: true
      CLOUDSQL_CONNECTION_NAME:
        required: true
      DB_USERNAME:
        required: true
      DB_PASSWORD:
        required: true
      DB_HOST:
        required: true
      DB_PORT:
        required: true
      DB_NAME:
        required: true
      RABBITMQ_USERNAME:
        required: true
      RABBITMQ_PASSWORD:
        required: true
      RABBITMQ_VHOST:
        required: true
      RABBITMQ_ADDRESSES:
        required: true
      JWT_SECRET:
        required: true
      JWT_EXPIRATION:
        required: true
    

jobs:
  build-test:
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/build-steps.yml@main
    with:
      service-name: ${{ inputs.service-name }}

  docker-build-push:
    needs: build-test
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/docker-build-push.yml@main
    with:
      service-name: ${{ inputs.service-name }}
    secrets: inherit

  deploy-to-gke:
    needs: docker-build-push
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/deploy-to-gke.yml@main
    with:
      service-name: ${{ inputs.service-name }}
      container-port: ${{ inputs.container-port }}
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_CLUSTER_NAME: ${{ secrets.GCP_CLUSTER_NAME }}
      CLOUDSQL_CONNECTION_NAME: ${{ secrets.CLOUDSQL_CONNECTION_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      RABBITMQ_VHOST: ${{ secrets.RABBITMQ_VHOST }}
      RABBITMQ_ADDRESSES: ${{ secrets.RABBITMQ_ADDRESSES }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}