name: Build and Deploy Java Spring Boot Service

on:
  push:
    branches:
      - main

jobs:
  build-test:
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/build-steps.yml@main
    with:
      service-name: AuthService

  setup-cloud:
    needs: build-test
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/setup-cloud.yml@main
    secrets: inherit

  docker-build-push:
    needs: setup-cloud
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/build-and-push.yml@main
    with:
      service-name: AuthService
    secrets: inherit

  deploy-to-gke:
    needs: docker-build-push
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/deploy-to-gke.yml@main
    with:
      service-name: AuthService
      container-port: "8080"
    secrets: inherit
