name: Build and Deploy Java Spring Boot Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      container-port:
        required: false
        type: string
        default: "8080"
    secrets:
      GCP_SA_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true
      GCP_REGION:
        required: true
      GCP_CLUSTER_NAME:
        required: true
      CLOUDSQL_CONNECTION_NAME:
        required: true
      DB_USERNAME:
        required: true
      DB_PASSWORD:
        required: true
      DB_HOST:
        required: true
      DB_PORT:
        required: true
      DB_NAME:
        required: true

jobs:
  build-test:
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/build-steps.yml@main
    with:
      service-name: ${{ inputs.service-name }}

  docker-build-push:
    needs: build-test
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/docker-build-push.yml@main
    with:
      service-name: ${{ inputs.service-name }}
    secrets: inherit

  deploy-to-gke:
    needs: docker-build-push
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/deploy-to-gke.yml@main
    with:
      service-name: ${{ inputs.service-name }}
      container-port: ${{ inputs.container-port }}
    secrets: inherit
