name: Build and Test Java Spring Boot Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  build-and-test:
    uses: NUS-ISS-ASS-TEAM-9/Devops/.github/workflows/build-steps.yml@main
    with:
      service-name: ${{ inputs.service-name }}
