name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      dockerfile-path:
        required: false
        type: string
        default: Dockerfile
    secrets:
      GCP_PROJECT_ID:
        required: true
      GCP_REGION:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build JAR with Maven (with fallback)
        run: |
          if [ -f "./mvnw" ] && [ -f "./.mvn/wrapper/maven-wrapper.properties" ]; then
            echo "Using Maven Wrapper"
            chmod +x ./mvnw
            ./mvnw clean package -DskipTests
          else
            echo "Using system Maven"
            mvn clean package -DskipTests
          fi

      - name: Build and Push Docker Image
        run: |
          SERVICE_NAME_LOWERCASE=$(echo "${{ inputs.service-name }}" | tr '[:upper:]' '[:lower:]')
          REGION_URL="${{ secrets.GCP_REGION }}-docker.pkg.dev"

          docker build -f ${{ inputs.dockerfile-path }} \
            -t ${REGION_URL}/${{ secrets.GCP_PROJECT_ID }}/devops/${SERVICE_NAME_LOWERCASE}:$GITHUB_SHA .

          docker push ${REGION_URL}/${{ secrets.GCP_PROJECT_ID }}/devops/${SERVICE_NAME_LOWERCASE}:$GITHUB_SHA
