name: Housekeeping Artifact Registry (Keep 5)

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Prune old artifact images (retain 5 per image)
        run: |
          REGION="${{ secrets.GCP_REGION }}"
          PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
          REPO="devops"

          echo "Fetching images under: $REGION-docker.pkg.dev/$PROJECT_ID/$REPO"

          gcloud artifacts docker images list "$REGION-docker.pkg.dev/$PROJECT_ID/$REPO" \
            --include-tags \
            --format="value(IMAGE)" | sort | uniq | while read -r image_name; do

            echo "::group:: Checking image: $image_name"

            gcloud artifacts docker images list "$image_name" \
              --include-tags \
              --sort-by="~UPDATE_TIME" \
              --format="value(DIGEST)" | tail -n +6 | while read -r digest; do
                echo "Deleting old image: $image_name@$digest"
                gcloud artifacts docker images delete "$image_name@$digest" --quiet --delete-tags
              done

            echo "::endgroup::"
          done
