name: Update Manifests for Service

on:
  workflow_dispatch:
    inputs:
      update-ingress:
        description: 'Update Ingress manifest'
        required: true
        type: boolean
      update-service:
        description: 'Update Service manifest'
        required: true
        type: boolean
      update-hpa:
        description: 'Update HPA manifest'
        required: true
        type: boolean

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Set up kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Get Service Name from Repository Context
        id: get_service_name
        run: |
          SERVICE_NAME=${GITHUB_REPOSITORY##*/}
          SERVICE_NAME_LOWERCASE=$(echo "$SERVICE_NAME" | tr '[:upper:]' '[:lower:]')
          echo "SERVICE_NAME=$SERVICE_NAME_LOWERCASE" >> $GITHUB_ENV

      - name: Apply Ingress manifest
        if: ${{ inputs.update-ingress == 'true' }}
        run: |
          echo "Applying Ingress for service: ${{ env.SERVICE_NAME }}"
          kubectl apply -f devops/manifests/${{ env.SERVICE_NAME }}/ingress.yaml

      - name: Apply Service manifest
        if: ${{ inputs.update-service == 'true' }}
        run: |
          echo "Applying Service for service: ${{ env.SERVICE_NAME }}"
          kubectl apply -f devops/manifests/${{ env.SERVICE_NAME }}/service.yaml

      - name: Apply HPA manifest
        if: ${{ inputs.update-hpa == 'true' }}
        run: |
          echo "Applying HPA for service: ${{ env.SERVICE_NAME }}"
          kubectl apply -f devops/manifests/${{ env.SERVICE_NAME }}/hpa.yaml

      - name: Confirm Update Completion
        run: |
          echo "Manifests updated successfully."
